### ISSUE TITLE
Add generic versions of IXxInstrumentation interfaces

### ISSUE THREAD

**Issue by idg10** [corvus-dotnet/Corvus.Monitoring#14]
I'm considering augmenting interfaces such as [`IOperationsInstrumentation`](https://github.com/corvus-dotnet/Corvus.Monitoring/blob/master/Solutions/Corvus.Monitoring.Instrumentation.Abstractions/Corvus/Monitoring/Instrumentation/IOperationsInstrumentation.cs) by defining versions with a single type argument that identifies the source of the telemetry.

This is similar in concept to the relationship between [`ILogger`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.ilogger) and [`ILogger<T>`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.ilogger-1) in `Microsoft.Extensions.Logging`. The generic version derives from the non-generic one, and adds no new members. The generic form offers these benefits:

* Represents the "origin of data" concept through the type system
* Each log source can have its own logger instance in a way `Microsoft.Extensions.DependencyInjection` can handle cleanly

Systems that don't care about these features don't pay a large price. It's barely any more effort to use `ILogger<T>` than plain `ILogger`, and if you _really_ want to you can just use the non-generic `ILogger`.

For `Corvus.Monitoring` I'm mainly interested in the first benefit: I'd like it to be possible for telemetry to be tagged automatically with the origin. So if some class `FlumpSoft.Frobnicator` wants to provide operation telemetry, it would depend on `IOperationsInstrumentation<FlumpSoft.Frobnicator>`. We could supply a standard implementation of `IOperationsInstrumentation<T>` that defers to `IOperationsInstrumentation`, adding in an extra key/value pair to the properties, e.g. `{ "Corvus.InstrumentationSource", "FlumpSoft.Frobnicator" }`.

The second benefit—per-source instrumentation targets—is potentially of interest for filtering. For example, with logging it can make sense for different log targets to have different log levels set. In that scenario, per-source `ILogger<T>` instances can be particularly important because you want to enable components to avoid the overhead of chatty logging (lots of string allocations) in cases where nothing wants to see the log output. For that to work, components need to be able to ask "Is anything listening for `Debug` level logging from me?" and if the answer is no, it can avoid the allocations.

The downside of this is that the objects supplied to the components generating diagnostic information need to have some means of answering that question. Since we're currently intending to use EventFlow so as to be able to dispatch instrumentation to a wide variety of sources, it's not clear that we'd be able to answer that. The answer to the question "Will anything use this telemetry?" may end up being "It depends—we need to see the telemetry before being able to answer that question." If filtering is dependent on information in the dictionary of additional properties, then you end up doing the allocation work in any case, at which point there's nothing to be gained.

So I'm not currently thinking of providing a way for instrumentation to ask "Should I even bother with this?" (Although as ever I'm open to being swayed.) The addition of generic forms of these interfaces would make it possible, but it's not currently a goal of the design.

**Comment by mwadams** [comment]
I think this is worth doing for the first goal alone.

However, the second goal is interesting.

I'm just going to ramble here a bit to straighten the problem out in my head. There is the "cross-system boundary" problem, as well as the "in process" problem.

|| Producer | Sink || -T-R-A-N-S-P-O-R-T- || Consumers ||

Why produce the data if there are definitely no consumers on the far end (ever). Does the producer have any means of knowing it should be producing telemetry? Config is the way we do that for logging because it is (fairly) easily classified into "levels" - essentially from firehose to drip.

With Telemetry the vectors are more complex.

It feels rather like it might benefit from the "subject"/"interest" pattern we us in workflow, and some kind of central "registry".

As a **consumer**, I register that I am interested in particular subject matter and/or particular sources - perhaps with globbing. 

As a **producer**, I tag my telemetry with "subject matter" [basically just tags] and "source" . I can easily talk to an in-process API that gets and caches the register of interests, and answers the question "should I bother producing this telemetry".

And you might find that we have things like a sink-to-blob consumer that registers itself as interested in everything tagged with a well-known "baseline" subject, from all sources, for example. But add a sink that asks for everything for all particular subject area from all sources.

We might want to think about whether we bake in well-known notions like the "operation" or just leave those as conventions?

This feels like a whole separate piece of work, but one that would be very powerful with a very simple implementation.

**Comment by idg10** [comment]
That sounds like something I'd enjoy building. I'm not sure whether that counts as a mark for or against it. :)

For now I just want to look at what this means for the interfaces. Rather than decide right now whether we're definitely going to build all of that, I want to make sure that:

* it's possible to build all that
* it's possible to use these interfaces without building all of that

Adding `IOperationsInstrumentation<T>` et al looks like a good idea at this stage. It opens up interesting possibilities, but imposes very little overhead on users who don't want any of those possibilities.

The only question I have right now is: could there be some better way to achieve these ends? (If there are no objections by Wednesday, I'll remove the word "Consider" from the title of this issue.)
